version: '3.7'

services:
  etcd:
    container_name: "etcd"
    hostname: "etcd"
    image: bitnami/etcd
    environment:
      ALLOW_NONE_AUTHENTICATION:  yes
    expose:
      - "2379"
      - "2380"
    volumes:
      - "/Users/xingshanghe/docker/etcd/config:/opt/bitnami/etcd/conf"
      - "/Users/xingshanghe/docker/etcd/data:/bitnami/etcd/data"
    networks:
      - local

  minio:
    container_name: "minio"
    hostname: "minio"
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_PROMETHEUS_URL: http://prometheus:9090
      MINIO_ETCD_ENDPOINTS: http://etcd:2379
    links:
      - prometheus
      - etcd
    command: server /data{1...8} --console-address ':9001' --address ':9000'
    volumes:
      - "/Users/xingshanghe/docker/minio/data1:/data1"
      - "/Users/xingshanghe/docker/minio/data2:/data2"
      - "/Users/xingshanghe/docker/minio/data3:/data3"
      - "/Users/xingshanghe/docker/minio/data4:/data4"
      - "/Users/xingshanghe/docker/minio/data5:/data5"
      - "/Users/xingshanghe/docker/minio/data6:/data6"
      - "/Users/xingshanghe/docker/minio/data7:/data7"
      - "/Users/xingshanghe/docker/minio/data8:/data8"
    networks:
      - local

  prometheus:
    container_name: "prometheus"
    hostname: "prometheus"
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: /Users/xingshanghe/docker/prometheus/config/prometheus.yml
        target: /etc/prometheus/prometheus.yml
    networks:
      - local

networks:
  local:
    driver: bridge